import { makeStyles, Theme } from "@material-ui/core";

const useStyles = makeStyles((theme: Theme) => {
  return {
    wrapper: {
      width: "13%",
      display: "flex",
      flexDirection: "row",
      fontFamily: "gibson",
    },
    input: {
      height: 40,
      border: "1px solid #BBBBBB",
      borderRadius: 5,
      padding: "0 10px",
      color: "#0A208F",
      backgroundColor: "#fff",
      width: "80%",
      fontSize: 16,
      fontWeight: 400,
      marginRight: 4,
      outline: "none",
      background: "none",
      fontFamily: "gibson",
      "&::-webkit-outer-spin-button": {
        "-webkit-appearance": "none",
        margin: 0,
      },
      "&::-webkit-inner-spin-button": {
        "-webkit-appearance": "none",
        margin: 0,
      },
    },
    inputError: {
      height: 40,
      border: "1px solid red",
      borderRadius: 5,
      padding: "0 10px",
      color: "#0A208F",
      backgroundColor: "#fff",
      width: "80%",
      fontSize: 16,
      fontWeight: 400,
      marginRight: 4,
      fontFamily: "gibson",
      outline: "none",
      "&::-webkit-outer-spin-button": {
        "-webkit-appearance": "none",
        margin: 0,
      },
      "&::-webkit-inner-spin-button": {
        "-webkit-appearance": "none",
        margin: 0,
      },
    },
    hiddenInput: {
      height: 40,
      color: "#0A208F",
      borderRadius: 5,
      border: "none",
      outline: "none",
      backgroundColor: "#fff",
      width: "94%",
      fontSize: 16,
      fontWeight: 400,
      whiteSpace: "pre",
      overflow: "hidden",
      textOverflow: "ellipsis",
      fontFamily: "gibson",
    },
    inputFullname: {
      height: 40,
      border: "1px solid #BBBBBB",
      borderRadius: 5,
      padding: "0 20px",
      color: "#0A208F",
      fontFamily: "gibson",
      backgroundColor: "#fff",
      width: "80%",
      fontSize: 16,
      fontWeight: 400,
      outline: "none",
    },
    hiddenInputFullname: {
      height: 40,
      color: "#0A208F",
      borderRadius: 5,
      border: "none",
      outline: "none",
      backgroundColor: "#fff",
      width: "94%",
      fontSize: 16,
      fontWeight: 400,
      fontFamily: "gibson",
      paddingLeft: 20,
    },
    inputFullnameError: {
      height: 40,
      border: "1px solid red",
      borderRadius: 5,
      padding: "0 20px",
      color: "#0A208F",
      backgroundColor: "#fff",
      width: "80%",
      fontFamily: "gibson",
      fontSize: 16,
      fontWeight: 400,
      outline: "none",
    },
    saleStage: {
      height: 40,
      border: "1px solid #BBBBBB",
      borderRadius: 5,
      padding: "0 10px",
      color: "#0A208F",
      backgroundColor: "#fff",
      width: "80%",
      fontFamily: "gibson",
      fontSize: 16,
      fontWeight: 400,
      display: "flex",
      alignItems: " center",
      justifyContent: "space-between",
      position: "relative",
      "& img": {
        cursor: "pointer",
      },
      "& .modalSaleStage": {
        position: "absolute",
        top: "112%",
        left: "0",
        right: "0",
        zIndex: 999,
        width: 260,
        backgroundColor: "#fff",
      },
    },
    hiddenToken: {
      color: "#0A208F",
      fontFamily: "gibson",
    },
    hiddenSaleStage: {
      display: "flex",
      alignItems: " center",
      justifyContent: "space-between",
      height: 40,
      color: "#0A208F",
      borderRadius: 5,
      border: "none",
      outline: "none",
      fontFamily: "gibson",
      backgroundColor: "#fff",
      width: "94%",
      fontSize: 16,
      fontWeight: 400,
    },
    email: {
      position: "relative",
      cursor: "default",
      color: "#0A208F",
      width: "94%",
      "&> .formatEmail": {
        whiteSpace: "pre",
        overflow: "hidden",
        textOverflow: "ellipsis",
        fontFamily: "gibson",
      },
      "&> .valueEmail": {
        position: "absolute",
        visibility: "hidden",
        color: "white",
        opacity: 0,
        fontWeight: 400,
        fontSize: 14,
        minWidth: 100,
        backgroundColor: "#3FBCE9",
        borderRadius: 5,
        padding: "0 12px",
        top: "80%",
        left: 0,
        boxShadow: "rgba(0, 0, 0, 0.24) 0px 3px 8px",
        transition: "all 200ms",
        zIndex: 3,
        "&> p": {
          // opacity: 0.7,
        },
        " &::after": {
          content: '""',
          position: "absolute",
          display: "block",
          backgroundColor: "#3FBCE9",
          left: 10,
          top: -9,
          width: 10,
          height: 10,
          clipPath: "polygon(50% 20%, 0% 100%, 100% 100%)",
        },
      },
      "&:hover > .valueEmail": {
        visibility: "visible",
        opacity: 1,
      },
    },
  };
});

export default useStyles;
